automised more. ./run_from_python.sh -- -1 0 0 (for negative number input) and more

diff --git a/run_auto b/run_auto
--- a/run_auto
+++ b/run_auto
@@ -1,4 +1,4 @@
-#! /bin/sh -f
+#! /bin/sh #-f
 export RASPA_DIR=${HOME}/RASPA/simulations/
 export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
 export LD_LIBRARY_PATH=${RASPA_DIR}/lib
@@ -11,16 +11,14 @@ rm -rf Output
 rm -rf VTK
 rm -rf Restart
 
-# # Check if exactly three arguments are provided
-# if [ "$#" -ne 3 ]; then
-#     echo "Usage: $0 <number1> <number2> <number3>"
-#     exit 1
-# fi
-
 # run initial simulation
 awk '!found && /^RestartFile/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input 
 awk '!found && /^#CreateNumberOfMolecules/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
 $RASPA_DIR/bin/simulate $1 > /dev/null 2>&1
+
+# remove output files so they dont get interpreted as results if the 2nd simulation (restart) fails
+#rm -r Output/System_0/* # (the output of this initial simulation is random as the adsorbate is placed randomly)
+rm -rf Output
 
 # copy restart file
 cp -r Restart RestartInitial/
@@ -28,16 +26,21 @@ cp -r Restart RestartInitial/
 # delete (random) position of adsorbate created in initial simulation
 sed -i '' '/^Adsorbate-atom/d' RestartInitial/System_0/*
 # add desired adsorbate position to restart file
-echo "Adsorbate-atom-position: 0 0    5.0 0 0" >> RestartInitial/System_0/*
-#echo "Adsorbate-atom-position: 0 0    -1.54928252, 17.45034191, 12.71675087" >> RestartInitial/System_0/*
+#echo "Adsorbate-atom-position:  0 0 4.56 0.0 0.0" >> RestartInitial/System_0/* # hard coded
+echo "Adsorbate-atom-position:  0 0 0.0 0.0 0.0" >> RestartInitial/System_0/* # hard coded
+
 
 # restart simulation
 awk '!found && /^#RestartFile/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
 awk '!found && /^CreateNumberOfMolecules/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input    
 $RASPA_DIR/bin/simulate $1 > /dev/null 2>&1
 
-# print energy results:
-grep -m1 -A4 "Host/Adsorbate energy:" Output/System_0/* #outputs the total energy (Host/Adsorbent), the LJ part, the Coulomb part, the 
-#real part of the Coulomb and the fourier part of the Coulomb as text in seperate lines.
+# check if Output dir exists:
+if [ ! -d "Output/System_0" ]; then
+    echo "Error: Output directory not found. maybe simulations (restart) failed" >&2 # to stderr
+    exit 1
+fi
 
-grep -m1 "Alpha convergence parameter" Output/System_0/* # prints the alpha/kappa/smearing cooefficient RASPA used for the calculation
+# print energy results:
+grep -m1 -A4 "Host/Adsorbate energy:" Output/System_0/*
+#grep -m1 "Alpha convergence parameter" Output/System_0/* # prints the alpha/kappa/smearing cooefficient RASPA used for the calculation
